name: deepin-cd
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
    
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Preparing environment
      run: |
        sudo apt-get install rsync rclone
        
    - name: Preparing rclone
      run: |
        git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/wzwtt/secret.git /home/runner/secret
        ls
        mkdir ~/.config/rclone/
        cp ~/secret/rclone/rclone.conf ~/.config/rclone/
        sudo rm /etc/fuse.conf
        sudo cp ~/secret/rclone/fuse.conf /etc/fuse.conf
        mkdir ~/google
        nohup rclone mount google:/ ~/google  --umask 0000  --default-permissions  --allow-other  --attr-timeout 5m --vfs-cache-mode full --vfs-cache-max-age 6h --vfs-cache-max-size 10G --vfs-read-chunk-size-limit 100M  --buffer-size 300M &
        ls
    - name: syncing
      run: |
        rsync -avzP --delete-after rsync.deepin.com::releases/ ~/google/WebShared/mirrors/deepin-cd/
        
    - name: Calculating mirror size
      run: |
        git config --global user.email "wzwttol@outlook.com"
        git config --global user.name "wzwtt"
        git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/wzwtt/mirror-sync.git ~/mirror-sync
        cd ~/google/WebShared/mirrors/deepin-cd/
        du -sh > ~/mirror-sync/totalsize/deepin-cd.txt
        cd ~/mirror-sync/
        git add *
        git commit -m "total size"
        git push
        wget https://purge.jsdelivr.net/gh/wzwtt/mirror-sync@main/totalsize/deepin-cd.txt
